Fixed Application Crashes When Querying JSON from YAML
sirocco-ventures/raggenie pull request #100
Opened 2024-10-07 08:51 UTC by amilmshaji

Closes #99

2024-10-07 10:29 UTC, agberoz requested changes

2024-10-07 10:29 UTC, agberoz commented on app/chain/modules/ouput_formatter.py
Add a Loom video before & after issue

2024-10-08 13:08 UTC, agberoz approved these changes

2024-10-09 07:08 UTC, amilmshaji commented
Loom Video link:

<iframe src="https://www.loom.com/embed/6ab06c03aa6f4e54877a06dfd7694a24?sid=cffb2447-4320-47cf-82ae-b22e33f33165" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen style="position: absolute; top: 0; left: 0; width: 100%; height: 100%;"></iframe>

2024-10-09 07:11 UTC, amilmshaji commented
Loom Link:

https://www.loom.com/share/6ab06c03aa6f4e54877a06dfd7694a24?sid=4a3f11e7-c85d-45c6-9dd3-2f6656cda56a

2024-10-09 07:44 UTC, merged