Add docker-compose-yml
sirocco-ventures/raggenie pull request #102
Opened 2024-10-07 15:27 UTC by leinadsened

Add Docker Compose for running front- and back-end After running "docker-compose up --build" the app should be available on localhost:8080

2024-10-07 15:32 UTC, leinadsened commented
CLOSES #96

2024-10-08 06:46 UTC, ashmilhussain commented
I tried running this, but I’m encountering an error.
<img width="463" alt="Screenshot 2024-10-08 at 10 44 23 AM" src="https://github.com/user-attachments/assets/afcb0755-cb15-4e0f-9d30-7a3ef304f7fe">


In the case of Docker Compose, we already know the backendUrl. How should we handle this?

We don’t need an environment variable in this case, but it shouldn’t result in a failure either.

@agberoz  have a look

2024-10-08 08:00 UTC, leinadsened commented
I've found the problem, I have this version of the ui dockerfile:
![image](https://github.com/user-attachments/assets/7031b38d-e2e4-4977-a368-f3867260d2a7)
Can the frontend's dockerfile be modified or should I update the docker-compose?

2024-10-08 09:56 UTC, sethumadhavan-k commented
@leinadsened Set the environment variable as a build argument in the Dockerfile and pass it through the Docker Compose file.

2024-10-08 11:34 UTC, leinadsened commented
Hey @sethumadhavan-k I've updated both files, please let me know what you think.
I might misunderstand something, but shouldn't "VITE_API_URL=http://backend:8001" be added to the sample .env file?

2024-10-08 13:03 UTC, agberoz requested changes

2024-10-09 07:42 UTC, sethumadhavan-k submitted a review, later dismissed

2024-10-09 09:59 UTC, leinadsened commented on docker-compose.yml
> +        - VITE_API_URL=${VITE_API_URL}
Updated both files

2024-10-10 11:59 UTC, agberoz approved these changes

2024-10-10 12:00 UTC, merged