Add delete functionality for samples
sirocco-ventures/raggenie pull request #103
Opened 2024-10-08 06:06 UTC by zteezy19

Added delete functionality for issue #67. Used react-icons for trash icon for delete button. delete button is placed next to edit button.
Used the /api/v1/sqldelete/{id} API endpoint to perform the deletion.
Also added a confirmation prompt before deletion to prevent accidental removals using the confirmDialog function as well as some additional error handling.

2024-10-09 07:40 UTC, sethumadhavan-k requested changes

2024-10-09 11:00 UTC, zteezy19 commented
I've made the requested changes, thanks for the feedback. Please review it when you can @sethumadhavan-k

2024-10-09 11:11 UTC, sethumadhavan-k requested changes

2024-10-09 11:23 UTC, zteezy19 commented
Hi @sethumadhavan-k, I have adjusted as instructed. Sorry for the trouble

2024-10-09 11:41 UTC, sethumadhavan-k commented
@zteezy19  let me check

2024-10-11 04:55 UTC, sethumadhavan-k requested changes

2024-10-11 14:33 UTC, zteezy19 commented
Hi @sethumadhavan-k, I've changed the name of the confirmDailog function to confirmDialog to fix the typo, and also adjusted the usage of the function in the Samples.jsx. Please take a look thanks

2024-10-14 05:02 UTC, sethumadhavan-k commented
@zteezy19 The parameter of the confirmDialog function is not an object. Please ensure it follows the example provided, and for now, don't change the function name.

example :
confirmDailog("Are you sure you want to delete this?", "", {deleteicon}, {cancelicon}, {confirmButtonText}, {deleteButtononClickFunction})

2024-10-14 18:13 UTC, zteezy19 commented
Hi @sethumadhavan-k , I think I've adjusted as requested.

2024-10-15 04:45 UTC, sethumadhavan-k commented
@zteezy19  let me check this.

2024-10-15 13:22 UTC, sethumadhavan-k commented
@zteezy19 getting  this error in frontend 

<img width="1242" alt="Screenshot 2024-10-15 at 6 51 04 PM" src="https://github.com/user-attachments/assets/5866db2c-eb95-4c10-a09d-6bdef974fddb">

2024-10-15 13:26 UTC, sethumadhavan-k requested changes

2024-10-15 13:26 UTC, sethumadhavan-k commented on ui/src/services/Sample.js
> +  return DeleteService(`${API_URL}/sql/delete/${sampleId}`);
delelet API url is  sqldelete/{id} not sql/delete/{id}

2024-10-17 07:02 UTC, zteezy19 commented
Hi, I've fixed the API url typo.

2024-10-17 14:57 UTC, sethumadhavan-k commented
@zteezy19 let check

2024-10-17 16:02 UTC, sethumadhavan-k commented
@zteezy19 please update the sample delete  API url  `/sqldelete/{id}` also i am getting the same error 

<img width="1242" alt="Screenshot 2024-10-15 at 6 51 04 PM" src="https://github.com/user-attachments/assets/f893eae3-b90f-45b9-8e36-b15de393a841">

2024-10-17 18:29 UTC, zteezy19 commented
Hi, sorry, I did not commit the codes properly. The changes should be committed. so sorry for the newbie mistakes

2024-10-18 05:10 UTC, sethumadhavan-k commented
@zteezy19 please join on our slack channel https://join.slack.com/t/theailounge/shared_invite/zt-2ogkrruyf-FPOHuPr5hdqXl34bDWjHjw, i will assist there

2024-10-24 20:24 UTC, closed without merging