Add Alert Notification for Bot Restart After Configuration Changes
sirocco-ventures/raggenie pull request #110
Opened 2024-10-13 17:41 UTC by abhishekas7

### **Description**:

This PR introduces an alert notification to inform users that they need to restart the bot after saving any configuration changes. Currently, there are no clear instructions provided to users regarding this required action.

**Changes include**:
- Added a custom toast notification that appears after saving bot configurations.
- The notification displays: **"Please restart the bot to get changes to take effect."**
- A custom close button has been added to the toast for user control, as per the design.

### **Updates**:
- After a configuration is saved, users will now see a notification prompting them to restart the bot.

![image](https://github.com/user-attachments/assets/7433b9ca-d27b-4e39-beb0-8e929d91bd29)

![image](https://github.com/user-attachments/assets/641943ce-c119-411c-b028-b55603679e20)

2024-10-15 10:59 UTC, sethumadhavan-k requested changes

2024-10-15 10:59 UTC, sethumadhavan-k commented on ui/src/pages/ChatConfiguration/ChatConfiguration.jsx
> +              {
missing save success toast

2024-10-15 11:01 UTC, sethumadhavan-k commented
@abhishekas7 the bot restart notification will only appear if inference is added, as well as when there are any updates to inference.

2024-10-18 08:06 UTC, abhishekas7 commented
Video : https://www.loom.com/share/e89d13262bb247aa93036ed2b00ede2d?sid=07f3b32d-ae10-4c61-bbb4-817ed853550c

2024-10-21 04:51 UTC, sethumadhavan-k approved these changes

2024-10-22 05:19 UTC, merged