Add API Endpoint for Listing LLM Provider Models
sirocco-ventures/raggenie pull request #129
Opened 2024-10-17 07:01 UTC by sajosam

**Description:**

1. Implemented a new API to list available models for a given LLM provider.
2. This enhancement improves user access to LLM models by provider.

2024-10-17 11:58 UTC, agberoz requested changes

2024-10-17 11:58 UTC, agberoz commented on app/services/model_reader.py
> +import requests
Do these in Corresponding LLM loader classes

2024-10-17 18:11 UTC, agberoz requested changes

2024-10-17 18:11 UTC, agberoz commented on app/loaders/togethor/loader.py
> +            "Authorization": f"Bearer {self.model_config.api_key}",
Use self.model_config.get("api_key", "")

2024-10-17 18:11 UTC, agberoz commented on app/loaders/openai/loader.py
> +        }
Use self.model_config.get("api_key", "")

2024-10-17 18:12 UTC, agberoz commented
@sajosam , Attach postman screen shot of API response

2024-10-18 05:37 UTC, sajosam commented
@agberoz Here is the reponse,
![image](https://github.com/user-attachments/assets/4cd62daa-b98a-4992-ab4a-d37d1c49edce)

2024-10-18 06:04 UTC, agberoz submitted a review, later dismissed
LGTM

2024-10-18 06:40 UTC, ashmilhussain reviewed
@sajosam  check for unrelevent line and space additions

2024-10-18 06:40 UTC, ashmilhussain commented on app/api/v1/connector.py
> -
unwanted line changes

2024-10-18 07:15 UTC, sajosam commented
@ashmilhussain  The spacing changes were auto-corrected by the pre-commit linter.

2024-10-30 06:45 UTC, merged