API to test inference endpoint credentials #8
sirocco-ventures/raggenie pull request #13
Opened 2024-09-26 11:26 UTC by amilmshaji

Closes #8

2024-09-27 07:49 UTC, agberoz commented on app/loaders/ai71/loader.py
Standardize the response of the `get_response` method

2024-09-27 08:04 UTC, agberoz requested changes

2024-09-27 08:04 UTC, agberoz commented on app/services/provider.py
Remove the match case section and implement error handling in the model loader to restrict the use of unknown inference engines

2024-09-27 08:04 UTC, agberoz commented on app/services/connector_details.py
> +    inference_model = BaseLoader(model_configs= model_configs).load_model(inference.name)
Add a try-catch block here as the load_model may raise exception

2024-09-28 06:29 UTC, amilmshaji reviewed
Updated the mention corrections

2024-09-28 06:29 UTC, amilmshaji commented on app/services/provider.py
Removed unwanted amtch section and  implement error handling in the model loader

2024-09-28 06:29 UTC, amilmshaji commented on app/loaders/ai71/loader.py
standardized to dict return

2024-09-30 07:19 UTC, agberoz approved these changes

2024-09-30 08:35 UTC, merged