feat: Add support for multiple document loader plugins (PDF, YAML, TXT, DOCX)
sirocco-ventures/raggenie pull request #64
Opened 2024-10-01 12:18 UTC by sajosam

### Summary:
This PR adds support for loading and processing multiple document types (.pdf, .yaml, .txt, .docx). Uploaded files are validated and loaded into a vector store for further processing.

### Key Changes:
- Created a file upload handler class to support PDF, YAML, TXT, and DOCX file formats.
- Implemented file extension validation to ensure only supported formats are processed.
- Added a maximum file size limit of 10 MB to prevent large uploads.
- Enabled the ability to load data from multiple documents simultaneously into a vector store.

2024-10-01 12:19 UTC, sajosam commented on app/api/v1/connector.py
> +from fastapi import APIRouter, UploadFile, File
Import required library for upload documents

2024-10-01 12:20 UTC, sajosam commented on app/api/v1/connector.py
> +async def upload_document_datsource(
Async route function for upload documents

2024-10-01 12:20 UTC, sajosam commented on app/api/v1/connector.py
> +    error, size = await svc.fileValidation(file)
File validation checker

2024-10-01 12:24 UTC, sajosam commented on app/api/v1/connector.py
> +    result, error = await svc.upload_pdf(file)
Upload file to assets/datasource/documents/<uuid>/<file_name>

2024-10-01 12:25 UTC, sajosam commented on app/base/document_data_plugin.py
> +class DocumentDataPlugin(ABC):
Defined abstract method for DocumentDataPlugin

2024-10-01 12:26 UTC, sajosam commented on app/plugins/document/__init__.py
> +__version__ = '1.0.0'
Defined document plugins base details

2024-10-01 12:27 UTC, sajosam commented on app/plugins/document/__init__.py
> +__connection_args__ = OrderedDict(
Defined configuration params for document plugins

2024-10-01 12:27 UTC, sajosam commented on app/plugins/document/__init__.py
> +__prompt__ = Prompt(**{
Base prompt for document plugins

2024-10-01 12:27 UTC, sajosam commented on app/plugins/document/formatter.py
> +class Formatter:
Formatter class for document plugins

2024-10-01 12:28 UTC, sajosam commented on app/plugins/document/handler.py
> +class Document(BasePlugin, PluginMetadataMixin,DocumentDataPlugin,  Formatter):
Handler class for Document

2024-10-01 12:46 UTC, agberoz requested changes

2024-10-01 12:46 UTC, agberoz commented on app/services/connector.py
> +        }
connector docs may not be required here, as document type plugins don't have  documentation section

2024-10-01 12:46 UTC, agberoz commented on app/providers/data_preperation.py
>              for docs in self.documentation:
Try running the connector along with a database connector and ensure this conversion doesn't cause any issues

2024-10-01 12:46 UTC, agberoz commented on app/plugins/document/__init__.py
> +                "explanation": "Explain how you finalized the sql query using the schemas and rules provided",
wrong prompt

2024-10-01 12:46 UTC, agberoz commented on app/plugins/document/handler.py
> +        data = []
move this supported type into self.params

2024-10-02 12:46 UTC, sajosam commented
Link to Demo : https://www.loom.com/share/8b6c0d23bcb542dba526c424d24fc97c?sid=edb5bf30-b1a3-4beb-a454-14dc61dbe9be

2024-10-03 04:55 UTC, agberoz approved these changes

2024-10-03 04:56 UTC, agberoz approved these changes

2024-10-03 05:46 UTC, merged