Add Dockerfile for Backend App to Build and Run in Python
sirocco-ventures/raggenie pull request #68
Opened 2024-10-01 15:42 UTC by leinadsened

This was my first time using Docker, so take that as a warning, but I think I'm done.
Couldn't get onnxruntime to work with Alpine-based images, so I used Bookworm.

2024-10-03 04:44 UTC, agberoz requested changes

2024-10-03 04:44 UTC, agberoz commented on Dockerfile
> +# Use an official Python runtime as a parent image (Alpine-based)
Here's the updated comment with the additional environment variables:

---

Currently, the Docker image size is 1.75GB, and it can be optimized by following these steps to reduce it:

1. Use **multi-stage builds** to separate the build and deployment stages.
2. Use `python:3.11` as the **builder** image for creating the environment.
3. Set the following environment variables to improve performance and prevent the generation of `.pyc` files:
   ```dockerfile
   ENV PYTHONDONTWRITEBYTECODE=1
   ENV PYTHONUNBUFFERED=1
   ```
4. Copy only the `requirements.txt` file to the builder first to leverage Docker layer caching.
5. Create and activate a virtual environment in the builder stage:
   ```dockerfile
   RUN pip install virtualenv && virtualenv /opt/venv
   ENV PATH="/opt/venv/bin:$PATH"
   ```
6. Install dependencies inside the virtual environment.
7. Use `python:3.11-slim` as the **deployer** image for a smaller runtime environment.
8. Copy the virtual environment from the builder stage into the deployer stage and set bin bath for python in `venv` folder
   ```dockerfile
   COPY --from=builder /opt/venv /opt/venv
   ENV PATH="/opt/venv/bin:$PATH"
   ```
9. Copy the remaining application files and folders.
10. Expose the required port (the current default application port is 8001)
11. The **CMD** directive is optional and remove it for now; it can also be defined when running the container, which provides more flexibility. For example:
    ```bash
    docker run <image_name> python main.py llm
    ```

2024-10-03 18:38 UTC, leinadsened commented on Dockerfile
> +# Use an official Python runtime as a parent image (Alpine-based)
By following your review I've managed to reduce the image to 852 MB 😊

2024-10-04 18:30 UTC, agberoz requested changes

2024-10-04 18:30 UTC, agberoz commented on Dockerfile
> +# Copy the rest of the application code
Use `COPY . .` here

If you want to exclude certain files during the COPY  command, you can specify them in the .dockerignore file

2024-10-04 18:30 UTC, agberoz commented on Dockerfile
> +
Set a working directory here

`WORKDIR /app`

2024-10-04 18:32 UTC, agberoz commented on Dockerfile
> +
Once you make these two changes, your PR will be ready for merging.

Nice work

2024-10-05 10:34 UTC, agberoz approved these changes
LGTM

2024-10-05 12:54 UTC, ashmilhussain commented
@agberoz  didi you reveiw this ?

I'm not able to run the docker can you check again

1. virtualenv inside docker wont be required since docker itself is a container
2. i can't see the app running in this

2024-10-05 13:35 UTC, merged