Implement Base Testing Framework for Python Application
sirocco-ventures/raggenie pull request #80
Opened 2024-10-03 09:48 UTC by sajosam

This pull request establishes a foundational testing framework for the Python application to enhance testing capabilities for future development.

**Changes Made:**
Created a basic structure to support:
1. Integration Testing
2. Functional Testing
3. Unit Testing

2024-10-17 05:55 UTC, agberoz requested changes

2024-10-17 05:55 UTC, agberoz commented on app/tests/conftest.py
> +from typing import Generator, Any
can you move `tests` folder to base directory

2024-10-17 05:55 UTC, agberoz commented on app/tests/conftest.py
> +import pytest
Add documentation for testing instructions in Readme.md

2024-10-17 13:45 UTC, sajosam commented
@agberoz 
- Added test file to root directory
- Added readme file for testing
![image](https://github.com/user-attachments/assets/0ffc11bd-62ba-4d64-ab5c-5c1383e99b9c)
![image](https://github.com/user-attachments/assets/f0d49617-cf64-4792-ad98-253e39392da6)

2024-10-17 14:44 UTC, agberoz commented on tests/README.md
> +## Requirements
add dependency with version to requirement.txt

2024-10-18 05:11 UTC, agberoz approved these changes
LGTM

2024-10-22 05:22 UTC, merged