Implement Basic Authentication Middleware
sirocco-ventures/raggenie pull request #83
Opened 2024-10-03 12:21 UTC by sajosam

This pull request introduces a basic authentication middleware to manage user authentication in the application, while ensuring that chat routes remain exempt from the authentication process.

**Changes Made:**
1. Loaded username and password from environment variables for authentication.
2. Developed middleware to handle authentication for required routes.
3. Excluded chat routes from authentication checks to maintain accessibility.

2024-10-03 12:40 UTC, agberoz requested changes

2024-10-03 12:40 UTC, agberoz commented on app/api/v1/commons.py
> +
If you want to us environment variables, define it though config provider

2024-10-03 12:40 UTC, agberoz commented on app/api/v1/commons.py
> +
create a separate python file for auth router

2024-10-03 12:40 UTC, agberoz commented on app/utils/authlogin.py
> +
initialize class using these parameters

2024-10-03 12:40 UTC, agberoz commented on app/utils/authlogin.py
> +
Move jwt operation to utils

2024-10-03 12:40 UTC, agberoz commented on app/utils/authlogin.py
> +
move this method into utils

2024-10-03 12:52 UTC, agberoz requested changes

2024-10-03 12:52 UTC, agberoz commented on app/main.py
> +    auth_middleware = AuthMiddleware()
add middleware based on a configuration variable

2024-10-04 06:13 UTC, agberoz requested changes

2024-10-04 06:13 UTC, agberoz commented on app/api/v1/auth.py
> +    print(user.username, user.password)
no print statements pls

2024-10-04 06:13 UTC, agberoz commented on app/main.py
please use meaning full names

configs.auth_enabled and should be bool

2024-10-04 06:13 UTC, agberoz commented on app/providers/config.py
> +    # Auth
please use lowercase for variables please

2024-10-04 06:13 UTC, agberoz commented on app/utils/authlogin.py
> +    def __init__(self):
don't access configs inside

2024-10-04 06:13 UTC, agberoz commented on app/utils/authlogin.py
> +    def __init__(self):
pass these while initializing

2024-10-04 09:23 UTC, agberoz requested changes

2024-10-04 09:23 UTC, agberoz commented on app/utils/jwt.py
> +    def create_access_token(self, data: dict, expires_delta: timedelta = timedelta(minutes=30)):
create_jwt_token

2024-10-04 09:23 UTC, agberoz commented on app/utils/jwt.py
> +    def decode_access_token(self, token: str):
decode jwt token

2024-10-05 08:43 UTC, agberoz requested changes

2024-10-05 08:43 UTC, agberoz commented on app/utils/jwt.py
> +
move this into providers/middleware.py

2024-10-05 14:57 UTC, agberoz commented on app/utils/jwt.py
> +
verify_token method

2024-10-05 14:59 UTC, agberoz requested changes

2024-10-05 14:59 UTC, agberoz commented on app/utils/jwt.py
> +    def __init__(self, secret_key, algorithm):
pass algorithm default value as "HS256"

2024-10-18 05:13 UTC, agberoz requested changes

2024-10-18 05:13 UTC, agberoz commented on app/api/v1/auth.py
> +
use middleware output here

2024-10-18 06:05 UTC, agberoz commented
@abhishekas7  loom video ?

2024-10-18 12:01 UTC, abhishekas7 commented
**Loom video** 

https://www.loom.com/share/c7adf40921b74c07a75fbe29d51cb7b4?sid=d19e084f-42ec-43b4-8f53-d6b9ae64c677

2024-10-18 12:10 UTC, abhishekas7 commented
**Screenshots**

![image](https://github.com/user-attachments/assets/03a94881-dcf4-432c-b378-d41705a252a4)
![image](https://github.com/user-attachments/assets/6f41d55d-70b7-4146-8228-7fcd77549f93)

2024-10-21 04:53 UTC, agberoz submitted a review, later dismissed
LGTM

2024-10-23 12:44 UTC, abhishekas7 commented
Loom Record : https://www.loom.com/share/eed0172af29c4b0697ddcf7f5e9dcb82?sid=bf7e34ce-9f5f-484b-a19f-00a3eadbf15d

2024-10-30 06:49 UTC, merged